# How many distinct terms are in the sequence generated by a^b 
# for 2 <= a <= 100 and 2 <= b <= 100?

import numpy as np

terms = []

for a in range(2,101):
	for b in range(2,101):
		terms.append(a ** b)

terms = np.unique(terms)

print len(terms)